.TH IBTEST 1 "MARCH 2006" Linux "User Manuals"
.SH NAME
ibtest \- A utility to communicate with Gpib controlled devices
.SH SYNOPSIS
.B ibtest
.SH DESCRIPTION
.B ibtest
is a simple utility program to test a Gpib controlled device.
All of the device commands can be executed through it. Strings
can be written to and read from the devices and much more.
.SH OPTIONS
No command line options
.SH BUGS
No known bugs.
.SH AUTHOR
Gudjon I. Gudjonsson <gudjon@gudjon.org>
